### ISSUE TITLE
Define project goals

### ISSUE THREAD

**Issue by DMajrekar** [opencontrolplane/documentation#3]
We need to update the docs to define what is in and out of scope for this project. As a starter list:

Goals:

- Unified interface between cloud providers
- API End points to be hosted by providers, not users (Interim solution could allow users to self host, but this is not what we really want)
- Ability to manage resources outside of traditional cloud infra, e.g. Domain Name registrations
- Create a unified dev / DevOps experience through `kubectl` only

Out of Scope:

- Replacement for GitOps tools such as Crossplane / ArgoCD / Flux. Continuous watching and reconciliation of resources it not part of this project. However, these tools would interact with Cloud Providers using an OpenCP compatible interface

**Comment by alejandrojnm** [comment]
I put this in the readme, I think for now is ok, we can add more late if we need it.
