### ISSUE TITLE
Manage changes and enhancements with a process similar to KEPs

### ISSUE THREAD

**Issue by DMajrekar** [opencontrolplane/documentation#4]
As we add and develop OpenCP, we need an open and accountable framework for ensuring changes are made for the good for the project as a whole

I suggest we follow a style / process similar to k8s with their KEPs.

**Comment by alejandrojnm** [comment]
Can you point me in the right direction?

**Comment by alejandrojnm** [comment]
Do we need to follow this https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/0000-kep-process/README.md ?

**Comment by kaihoffman** [comment]
I can put this together @alejandrojnm

**Comment by kaihoffman** [comment]
I have put together resources for this at https://github.com/opencontrolplane/documentation/tree/main/enhancement-proposals

Closing this for now but feel free to re-open if there are further additions to be made.
